### ISSUE TITLE
[BUG] Application crashes when it reopen GymkInfoFragment

### ISSUE THREAD

**Issue by NEKERAFA** [gymkhanachain/GymkhanaChain#13]
**Describe the bug**
When I started to play a new gymkhana and exited it, the app returns to main activity. I pressed the gymkhanas and the App crashed.

**Log result**
```
2019-05-16 18:58:48.705 32235-32235/com.gymkhanachain.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.gymkhanachain.app, PID: 32235
    java.lang.IllegalStateException: Can't change container ID of fragment GymkInfoFragment{e07536c #3 id=0x7f0900c8 GymkInfoFragment}: was 2131296456 now 2131296376
        at android.support.v4.app.BackStackRecord.doAddOp(BackStackRecord.java:422)
        at android.support.v4.app.BackStackRecord.replace(BackStackRecord.java:444)
        at android.support.v4.app.BackStackRecord.replace(BackStackRecord.java:434)
        at com.gymkhanachain.app.ui.mainscreen.activities.MainActivity.onNearGymkhanaClick(MainActivity.java:315)
        at com.gymkhanachain.app.ui.mainscreen.fragments.NearGymkFragment.onNearGymkItemClick(NearGymkFragment.java:131)
        at com.gymkhanachain.app.ui.mainscreen.adapters.NearGymkAdapter$1.onClick(NearGymkAdapter.java:95)
        at android.view.View.performClick(View.java:6294)
        at android.view.View$PerformClick.run(View.java:24774)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6543)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Smartphone (please complete the following information):**
 - OS version: Android 8.1
 - APK version:

**Comment by Aletibazo** [comment]
Corregido en commit 42906100502cc7dd92b985baeeeea4e0d7dffe0c
